apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my_app:latest  # Adjust the image name
        ports:
        - containerPort: 3000
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: DOMAIN
        - name: PORT
          value: "3000"
        - name: STATIC_DIR
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: STATIC_DIR
        - name: PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: PUBLISHABLE_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: SECRET_KEY

