apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 3000         # Internal service port (inside the cluster)
      targetPort: 3000    # Container port (in the pod)
      nodePort: 30001     # External port for access (outside the cluster)

